### ISSUE TITLE
Add CLI for easier local testing

### ISSUE THREAD

**Issue by tommy-mitchell** [ehmicky/get-bin-path#21]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

When developing a CLI, there’s always a bit of overhead in testing manually by having to type `node cli.js …` (or more for nested paths). This isn’t hard to do, but it adds noise and can get cumbersome in certain situations.

### Describe the solution you'd like

Adding a command like `bin-path …` would both make manual testing a CLI easier, and ensure that you’re matching the behavior of your tests.

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by tommy-mitchell** [comment]
If you’d rather not have this be a part of this module, I’d be happy to make a standalone repo for it.

**Comment by ehmicky** [comment]
Hi @tommy-mitchell,

That's an interesting idea. However, wouldn't [`npm link`](https://docs.npmjs.com/cli/v6/commands/npm-link) be easier? I personally use this to test my CLIs. One pro this has is that you could type `my-cli ...` directly instead of prefixing it as `bin-path my-cli ...`.

**Comment by tommy-mitchell** [comment]
I think that `bin-path` would be the same as `npm link && my-cli`, you wouldn’t have to repeat the command name.

I’m always hesitant to use `npm link` because I’m never sure how it interacts with the global path, but that’s also just me not being familiar with it. What happens if you have a CLI globally installed (so it’s on your path), and then you fork it to make changes and run `npm link` - does it use the local command, or the global one?

**Comment by ehmicky** [comment]
`npm link` can be done just once, then you can do `my-cli` (as opposed to `npm link && my-cli`) each time you call the command.

The idea of `npm link` is to create a symlink from your global binary directory to your local project, so that your local binary can be used as if it had been installed globally.

For example, on my machine (I use Linux + nvm), it results in the following symlinks:
  - `~/.nvm/versions/node/v19.8.1/bin/my-project` -> `~/.nvm/versions/node/v19.8.1/lib/node_modules/my-project/path/to/bin.js`
  - `~/.nvm/versions/node/v19.8.1/lib/node_modules/my-project/` -> `/path/to/my-project/`

nvm puts `~/.nvm/versions/node/v19.8.1/bin` in `PATH`. 

The result: when I enter `my-project ...`, it executes `/path/to/my-project/path/to/bin.js`.

Having a project both installed globally and `npm link`'d is quite an edge case that I personally have not needed so far. In general, I only want to run the latest commit of my local project, not the latest npm published version. If I did want the latter, I would use `git checkout` on my local project.

So, overall, it works pretty well for me. The only hickup is that you need to run `npm link` once per Node.js version when you use nvm, but that's pretty alright IMHO.

**Comment by tommy-mitchell** [comment]
> `npm link` can be done just once, then you can do `my-cli` (as opposed to `npm link && my-cli`) each time you call the command.

Right, sorry, was just demonstrating. However, this actually would be different because `bin-path` would only run the local command, not any global ones. I personally don't want my local projects to be linked globally, I'd rather install a global version of it and update that (especially if my local version is in between working versions).

**Comment by ehmicky** [comment]
> this actually would be different because bin-path would only run the local command, not any global ones.

To be precise, `npm link` would run the local command, albeit through a global symlink. In other words, `bin-path` would execute the same binary file as `npm link`.

> I personally don't want my local projects to be linked globally, I'd rather install a global version of it and update that (especially if my local version is in between working versions).

To better understand your use case: is this because you want to be able to do both of the following?
  - Run your local version "in between working versions" for local testing -> `bin-path my-binary ...`
  - Use your project locally, not for testing, but for actual usage -> `my-binary ...` (global binary)

**Comment by tommy-mitchell** [comment]
Correct, or even just a more convenient way to run a local binary that I won't even be installing globally. And to clarify, I'm envisioning that `bin-path` would run the local binary without having to specify it's name:

```sh
bin-path --some-flag arg1 arg2
```

This would be the same as `npx my-binary` if it was installed as a dependency instead.

Perhaps a way to specify which binary to run (like [`npx -p my-binary my-other-binary`](https://stackoverflow.com/a/53573072/10292952)) would be useful as well.

**Comment by ehmicky** [comment]
You could temporarily change the `package.json` `name` while you run `npm link`. Like this, the global symlink would not overwrite the globally installed version of the package, and you would have two different commands to use, one to run the most recent commit, one to run the most recent published version.

However, I can see how installing `bin-path` globally once is simpler than having to do the above for each package.

It's quite an edge case, so I don't think I would create that package. However, if you want to create it, please feel free to ping me, and I'll be glad to link to it from this project's `README.md`. What do you think?

**Comment by tommy-mitchell** [comment]
Works for me :) I can see how this is a niche issue, lol. Feel free to close this.

**Comment by ehmicky** [comment]
One thing you would want to make sure is to use `stdio: 'inherit'` for stdin/stdout/stderr on the `child_process` executed by `bin-path`. This is the only way to keep the terminal as TTY (if it is TTY). Using `pipe` results in the child process's terminal being always non-TTY, which results in many different issues.

The `shell` option should also not be used, to avoid the shell being an intermediary proxy. Finally, `argv` should be passed as is.

I am basing this on having built similar CLIs like [`nve`](https://github.com/ehmicky/nve) which also proxies a command, and also on some experience co-maintaining [Execa](https://github.com/sindresorhus/execa). :)

**Comment by tommy-mitchell** [comment]
Thanks for the advice!

**Comment by ehmicky** [comment]
@all-contributors Can you please add @tommy-mitchell for idea?

**Comment by tommy-mitchell** [comment]
@ehmicky here's a first attempt: https://github.com/tommy-mitchell/bin-path-cli

---

Edit - here's a demo with [`listr-cli`](https://github.com/tommy-mitchell/listr-cli):

![demo](https://user-images.githubusercontent.com/1403701/226512937-a50538d5-c938-4d2b-b85f-8b97283e5323.gif)

**Comment by ehmicky** [comment]
This is looking great!

The only thing I noticed is that the exit code is not forwarded. For example, if the underlying binary has exit code `3`, it becomes `1` instead. You could re-use the underlying exit code by using [`error.exitCode`](https://github.com/sindresorhus/execa#exitcode).

I also added `bin-path-cli` to [this repository's `README.md`](https://github.com/ehmicky/get-bin-path/#see-also). 

Great work!

**Comment by tommy-mitchell** [comment]
Thanks :) Good catch, I've fixed that.
