### ISSUE TITLE
Fail if named binary isn't found

### ISSUE THREAD

**Issue by tommy-mitchell** [ehmicky/get-bin-path#23]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

From the description of [`options.name`](https://github.com/ehmicky/get-bin-path#optionsname), it sounds like `get-bin-path` would search specifically for the given named binary:

> Name of the binary. Only needs to be specified when the package exports several binaries.

However, `getRelativeBinPath` short-circuits to the default unnamed binary if `bin` is a string:

https://github.com/ehmicky/get-bin-path/blob/30e582ebca9379bf310e5048be5d98782375e80e/src/bin.js#L15-L20

### Describe the solution you'd like

I think a "strict names" or something option would be good to add, that causes `get-bin-path` to error if `options.name` doesn't match any named binaries, or the name of the project if `bin` is a string. (Similar for `directories.bin`, but I'm not familiar with how it works.)

This would be useful for `bin-path-cli`, because I'm adding a feature that attempts to use the first argument to find a named binary, and removes said argument if the given binary is found. However, `getBinPath()` returning the default binary causes this to fail.

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @tommy-mitchell,

Thanks, that's interesting.

I just went back to the logic and fixed a few problems, and released it as [`9.0.0`](https://github.com/ehmicky/get-bin-path/releases/tag/9.0.0).

When the `package.json` uses a `bin` field that is a string, `npm` uses the `package.json` `name` field as the binary name. Therefore, I would not consider it to be unnamed. For example:

```json
{
  "name": "example",
  "bin": "path/to/bin.js"
}
```

Is equivalent to:

```json
{
  "name": "example",
  "bin": {
    "example": "path/to/bin.js"
  }
}
```

Based on this, I have changed the behavior to the following: when the `name` option is used and the `package.json` `bin` is a string, `undefined` is returned if the `name` option is different from the `package.json` `name`. In the above example, `getBinPath()` and `getBinPath({ name: 'example' })` now return `path/to/bin.js`, but `getBinPath({ name: 'other' })` now returns `undefined`. I think this should fix your issue (although in a different way than suggested)?

When it comes to erroring when the `name` option does not match any binary, I would prefer this to be done by the consumer instead. Since `get-bin-path` returns `undefined` when no binary can be found, and the consumer should know whether an `name` option is passed, they should be able to throw an error in that case. Shifting that logic to the consumer would help keeping the API small.

Please let me know what you think.

**Comment by tommy-mitchell** [comment]
That works great! I agree that it's better to return `undefined`, my suggestion was for if the behavior didn't change. Thanks.

**Comment by ehmicky** [comment]
Thanks again for raising this issue. This allowed me to question the current logic and improve it! :rocket:
