### ISSUE TITLE
What’s a good way to use this in a TypeScript project?

### ISSUE THREAD

**Issue by tommy-mitchell** [ehmicky/get-bin-path#28]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

This library works great for testing CLIs written in plain JS, but with a build step (such as with TS), tests can only be run on the built solution. If I set my tests up to use a transpiler like `ts-node` or `tsx`, that means I don’t get to use `get-bin-path` at all.

### Describe the solution you'd like

Maybe there could be an option to rewrite the base path?

```jsonc
// package.json

{
  "bin": "dist/cli.js"
}
```

```ts
// test.ts

const binPath = await getBinPath({rewritePath: "src"});
//=> "src/cli.ts"
```

The option needs a better name, of course.

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @tommy-mitchell,

I think this feature makes sense. However, I think the rewrite should be done at the user level, not this library:

```ts
// test.ts

const binPath = (await getBinPath()).replace('dist', 'src');
//=> "src/cli.ts"
```

While most build steps just move code from some source directory to a build directory, some setups are more complex. I would ideally like to keep this package small and focused, with as few options as possible. This seems to be a case where it might be more appropriate for this logic to be done on the consumer side instead of the library.

**Comment by tommy-mitchell** [comment]
@ehmicky what do you think of https://github.com/tommy-mitchell/bin-path-cli/pull/5? I run into wanting to use the source binary a lot, but I'm not sure if this approach makes the most sense:

```sh
npx bin-path dist.js:::src.ts some-arg --some-flag
```

**Comment by ehmicky** [comment]
I think this works well within `bin-path-cli`. :+1:
